### ISSUE TITLE
Add 'id' to all log messages from a source

### ISSUE THREAD

**Issue by groma84** [rxjs-debug/rxjs-debug#2]
In a very large system with lots of log output (that goes to console when in debug mode) it gets hard to actually catch the parts between the "START" and "END" log messages as only those contain the 'id' I assigned. Everything else gets intertwined with any other log messages without something I can easily filter for.

It would be really great if the id could (optionally?) be prepended to all log messages.

P.S.: Super awesome project!!

**Comment by dabalyan** [comment]
@groma84 thanks for your interest in rxjs-debug, and opening this issue.

If I understood it correctly, you want the id to be also included with operators' logs?
It's intentionally not included with every operator as they are always grouped, and the group has the provided id. You can safely assume that all the operators belong to the same stream if another group hasn't interrupted it. Also, when a group resumes or starts it always has 3 new-lines before it to separate it from the any other logs.

To illustrate what I mean, I created a [StackBlitz demo](https://stackblitz.com/edit/rxjs-debug-playground-qsrvxo) with two streams running simultaneously, you can see its output in the image below. stream **A** has a delay and got interrupted by stream **B**, but then Stream **A** continues again and the id (i.e. **A**) is printed just before printing the operators.
![Screenshot 2020-11-18 203334](https://user-images.githubusercontent.com/17353112/99579029-f2072d80-29dd-11eb-9fd0-a351362121c1.png)

Does this address your problem?
If not, can you please add an example by forking [this StackBlitz template](https://stackblitz.com/edit/rxjs-debug-playground-qsrvxo) that I created for the image above, and maybe also include a screenshot maybe. So that I can better understand the problem.

**Comment by groma84** [comment]
An example would be something like this:
![image](https://user-images.githubusercontent.com/5436432/99631808-81dbc480-2a3c-11eb-94b9-b6c7f03a9329.png)

If I want to only look at my rxjs-debugged observables I can not just filter for "iCanFilterForThis" in the debug tools, because then the operator logs are removed, too.

And the other log messages are too diverse to filter them out with negative filters in the debug tools thus I am stuck with scrolling through a lot of noise.

**Comment by groma84** [comment]
Oh, and if you greenlight the change I can try my luck with a PR for it if you want. This is an awesome library already!

**Comment by dabalyan** [comment]
okay now I understand what the actual problem is, it's not just operators, you want to be able filter for `rxjs-debug` logs.
I have a few ideas regarding that, and I also plan to make the logs more organized, give me some time (maybe this weekend).

Thanks for offering the help, but I don't have any contribution guidelines setup yet, which would take me some time.
Hope you understand :)

**Comment by dabalyan** [comment]
hey @groma84 just released **1.3.0** with a prefix `➰` added to every `rxjs-debug` log, so that you can easily filter it.
If it solves your issue, can we close it?

**Comment by groma84** [comment]
Yeah, that solves the issue for me.

Thanks for the change!
